### ISSUE TITLE
npm example

### ISSUE THREAD

**Issue by Snake4life** [mattconsto/fantasy-names#1]
hey could you give some examples how to use it with npm?

e.g. diablo female

**Comment by mattconsto** [comment]
Sure, I'm currently working on a bug fix to get it working properly. I'll update once I've pushed the changes.

**Comment by mattconsto** [comment]
I've pushed an update fixing some issues preventing it from working properly with node, and here is how to use it. If you want to use the script as a command line tool install the script globally like so:

npm install fantasy-names -g
fantasy-names diablo demons 10 0

Otherwise if you want to use it as a node dependency, install the script locally like so:

npm install fantasy-names
echo -e "var names = require('fantasy-names');\nconsole.log(names('diablo', 'demons', 10, 0));" > names.js
node names.js

I'm going to mark this as resolved, if you need any further help just ask.

**Comment by Snake4life** [comment]
greate thank you very much!
