### ISSUE TITLE
Generating names with a seed?

### ISSUE THREAD

**Issue by Nesh108** [mattconsto/fantasy-names#2]
Hello,

I found this library very well-done and I would like to know if there is a way to generate a name through a seed.

This would be something like: 

```
var MY_SEED = "AA00BB11CC22";
var name_from_seed = require('fantasy-names');
console.log(name_from_seed('diablo', 'demons', MY_SEED));  // 'Devil'
console.log(name_from_seed('diablo', 'demons', MY_SEED));  // 'Devil'
console.log(name_from_seed('diablo', 'demons', MY_SEED));  // 'Devil'
console.log(name_from_seed('diablo', 'demons', MY_SEED));  // 'Devil'
console.log(name_from_seed('diablo', 'demons', MY_SEED));  // 'Devil'
console.log(name_from_seed('diablo', 'demons', MY_SEED));  // 'Devil'
console.log(name_from_seed('diablo', 'demons', MY_SEED + "1"));  // Not 'Devil'
```

So, a specific seed can be connected to a specific name and back.

**Comment by mattconsto** [comment]
Currently there isn't one, however it's an interesting idea. Right now I don't know how soon I could work on it but I would happily accept a pull request if done well. Thinking about it, here is what would need to be done:

1. Use `sed` to remove `i = Math.floor(Math.random() * 10); {`, and the trailing }
2. Use `sed` to replace `function generator$########$#######(type) {` with something like `function generator$########$#######(type, seed) {\nseed = seed || Math.floor(Math.random() * 10);`
3. Intelligently replace all occurrences of i with seed, or be lazy and don't bother.
4. Prettify and reminify the generators.
5. Update the bootstrap to properly handle the seed, passing a random number between 0 and 10 each call.

It needs to be between 0 and 10 because of the origin on these scripts.

**Comment by mattconsto** [comment]
I just finished adding the seed and pushing to git+npm, and in the end it turned out easier than expected thanks to [davidbau/seedrandom](https://github.com/davidbau/seedrandom)'s hard work. I'm curious what you are planning to use this for, assuming it's public.

One thing to note is that I decided to use a slightly different method signature, so you will need to supply the default values for both quantity and type:

```
var MY_SEED = "AA00BB11CC22";
var name_from_seed = require('fantasy-names');
console.log(name_from_seed('diablo', 'demons', 1, 0, MY_SEED));  // 'Devil'
console.log(name_from_seed('diablo', 'demons', 1, 0, MY_SEED + "1"));  // Not 'Devil'
```

**Comment by Nesh108** [comment]
Thanks for this!

I can quickly describe the idea: I want to create a small game system which would be able to generate random names and world elements given a seed. So, if another player uses the same seed, it would get the same elements and the same names for the NPCs. :D

**Comment by mattconsto** [comment]
Implementing this directly into the package was a bad idea and caused bloat and feature creep. If you want to seed Math.random use https://github.com/davidbau/seedrandom and this package will also be seeded.

**Comment by Nesh108** [comment]
Thanks for the reply!

I actually ended up changing the randoms to seed random, so the problem was solved 😄
